global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'url-shortener-monitor'

scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['url-shortener:5000']
        labels:
          service: 'url-shortener'
    metrics_path: '/metrics'
    scrape_interval: 5s
